# Generated by Django 5.2.1 on 2025-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dp',
            field=models.FileField(blank=True, default='default_images/default_dp2.jpeg', null=True, upload_to=''),
        ),
    ]
